lib/ecommerce_web/router.ex
defmodule EcommerceWeb.Router do
  use EcommerceWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, html: {EcommerceWeb.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EcommerceWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/items", ItemController
  end

  # Other scopes may use custom stacks.
  # scope "/api", EcommerceWeb do
  #   pipe_through :api
  # end

  # Enable LiveDashboard and Swoosh mailbox preview in development
  if Application.compile_env(:ecommerce, :dev_routes) do
    # If you want to use the LiveDashboard in production, you should put
    # it behind authentication and allow only admins to access it.
    # If your application does not have an admins-only section yet,
    # you can use Plug.BasicAuth to set up some basic authentication
    # as long as you are also using SSL (which you should anyway).
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: EcommerceWeb.Telemetry
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/ecommerce/application.ex
defmodule Ecommerce.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      EcommerceWeb.Telemetry,
      Ecommerce.Repo,
      {DNSCluster, query: Application.get_env(:ecommerce, :dns_cluster_query) || :ignore},
      {Phoenix.PubSub, name: Ecommerce.PubSub},
      # Start the Finch HTTP client for sending emails
      {Finch, name: Ecommerce.Finch},
      # Start a worker by calling: Ecommerce.Worker.start_link(arg)
      # {Ecommerce.Worker, arg},
      # Start to serve requests, typically the last entry
      EcommerceWeb.Endpoint
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Ecommerce.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    EcommerceWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/ecommerce/carrinho.ex
defmodule Ecommerce.Carrinho do
  @moduledoc """
  Carrinho de Ecommerce
  """

  import Ecto.Query, warn: false
  alias Ecommerce.Repo

  alias Ecommerce.Carrinho.Item

  @doc """
  Retorna uma lista de itens.

  ## Exemplos de uso

      iex> list_items()
      [%Item{}, ...]

  """
  def list_items do
    Repo.all(Item)
  end

  @doc """
  Obtem um unico objeto pelo id.

  Retorna `Ecto.NoResultsError` se o objeto não existir.

  ## Examplos

      iex> get_item!(123)
      %Item{}

      iex> get_item!(456)
      ** (Ecto.NoResultsError)

  """
  def get_item!(id), do: Repo.get!(Item, id)

  @doc """
  Cria um item

  ## Examplos

      iex> create_item(%{field: value})
      {:ok, %Item{}}

      iex> create_item(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_item(attrs \\ %{}) do
    %Item{}
    |> Item.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Atualiza um item.

  ## Exemplos

      iex> update_item(item, %{field: new_value})
      {:ok, %Item{}}

      iex> update_item(item, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_item(%Item{} = item, attrs) do
    item
    |> Item.changeset(attrs)
    |> Repo.update()
  end


  @doc """
  Exclui um item.

  ## Exemplos

      iex> delete_item(item)
      {:ok, %Item{}}

      iex> delete_item(item)
      {:error, %Ecto.Changeset{}}
  """
  def delete_item(%Item{} = item) do
    Repo.delete(item)
  end

  @doc """
  Retorna um `%Ecto.Changeset{}` para mapear as modificações feitas no objeto.

  ## Examplos

      iex> change_item(item)
      %Ecto.Changeset{data: %Item{}}

  """
  def change_item(%Item{} = item, attrs \\ %{}) do
    Item.changeset(item, attrs)
  end
end

lib/ecommerce/carrinho/item.ex
defmodule Ecommerce.Carrinho.Item do
  @moduledoc """
  O módulo `Ecommerce.Carrinho.Item` representa um item no carrinho de compras na aplicação Ecommerce.
  Ele usa Ecto para mapeamento de dados e validações de changeset.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @doc """
  Define o esquema para a tabela `items` no banco de dados.

  O esquema inclui os seguintes campos:
  - `:description`: uma string que descreve o item
  - `:name`: uma string que representa o nome do item
  - `:price`: um decimal que representa o preço do item
  """
  schema "items" do
    field :description, :string
    field :name, :string
    field :price, :decimal

    timestamps(type: :utc_datetime)
  end

  @doc """
  A função `changeset/2` é usada para validar e rastrear mudanças nos dados do item.

  Ela recebe dois argumentos:
  - `item`: a estrutura de dados atual do item
  - `params`: um mapa com as mudanças propostas para o item
  A função retorna um changeset que pode ser usado para atualizar o item no banco de dados.
  """
  def changeset(item, params) do
    item
    |> cast(params, [:name, :description, :price])
    |> validate_required([:name, :description, :price])
  end
end

lib/ecommerce/repo.ex
defmodule Ecommerce.Repo do
  use Ecto.Repo,
    otp_app: :ecommerce,
    adapter: Ecto.Adapters.Postgres
end

lib/ecommerce_web/controllers/item_controller.ex
defmodule EcommerceWeb.ItemController do
  use EcommerceWeb, :controller

  alias Ecommerce.Carrinho
  alias Ecommerce.Carrinho.Item

  def index(conn, _params) do
    items = Carrinho.list_items()
    render(conn, :index, items: items)
  end

  def new(conn, _params) do
    changeset = Carrinho.change_item(%Item{})
    render(conn, :new, changeset: changeset)
  end

  def create(conn, %{"item" => item_params}) do
    case Carrinho.create_item(item_params) do
      {:ok, item} ->
        conn
        |> put_flash(:info, "Item adicionado.")
        |> redirect(to: ~p"/items/#{item}")

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, :new, changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    item = Carrinho.get_item!(id)
    render(conn, :show, item: item)
  end

  def edit(conn, %{"id" => id}) do
    item = Carrinho.get_item!(id)
    changeset = Carrinho.change_item(item)
    render(conn, :edit, item: item, changeset: changeset)
  end

  def update(conn, %{"id" => id, "item" => item_params}) do
    item = Carrinho.get_item!(id)

    case Carrinho.update_item(item, item_params) do
      {:ok, item} ->
        conn
        |> put_flash(:info, "Item atualizado.")
        |> redirect(to: ~p"/items/#{item}")

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, :edit, item: item, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    item = Carrinho.get_item!(id)
    {:ok, _item} = Carrinho.delete_item(item)

    conn
    |> put_flash(:info, "Item deletado.")
    |> redirect(to: ~p"/items")
  end
end

lib/ecommerce_web/controllers/item_html.ex
defmodule EcommerceWeb.ItemHTML do
  use EcommerceWeb, :html

  embed_templates "item_html/*"

  @doc """
  Renders a item form.
  """
  attr :changeset, Ecto.Changeset, required: true
  attr :action, :string, required: true

  def item_form(assigns)
end

lib/ecommerce_web/controllers/page_controller.ex
defmodule EcommerceWeb.PageController do
  use EcommerceWeb, :controller


  def home(conn, _params) do
    render(conn, :home, layout: false)
  end

end

lib/ecommerce_web/components/cart/edit.html.eex
<h1>Editar Item</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.item_path(@conn, :update, @item)) %>

<span><%= link "Back", to: Routes.item_path(@conn, :index) %></span>

lib/ecommerce_web/components/layouts/app.html.heex
<header class="px-4 sm:px-6 lg:px-8">
  <div class="flex items-center justify-between border-b border-zinc-100 py-3 text-sm">
    <div class="flex items-center gap-4">
      <a href="/">
        <img src={~p"/images/logo.svg"} width="36" />
      </a>
      <p class="bg-brand/5 text-brand rounded-full px-2 font-medium leading-6">
        v<%= Application.spec(:phoenix, :vsn) %>
      </p>
    </div>
    <div class="flex items-center gap-4 font-semibold leading-6 text-zinc-900">
      <a href="https://twitter.com/elixirphoenix" class="hover:text-zinc-700">
        @elixirphoenix
      </a>
      <a href="https://github.com/phoenixframework/phoenix" class="hover:text-zinc-700">
        GitHub
      </a>
      <a
        href="https://hexdocs.pm/phoenix/overview.html"
        class="rounded-lg bg-zinc-100 px-2 py-1 hover:bg-zinc-200/80"
      >
        Get Started <span aria-hidden="true">&rarr;</span>
      </a>
    </div>
  </div>
</header>
<main class="px-4 py-20 sm:px-6 lg:px-8">
  <div class="mx-auto max-w-2xl">
    <.flash_group flash={@flash} />
    <%= @inner_content %>
  </div>
</main>

lib/ecommerce_web/components/layouts/root.html.heex
<!DOCTYPE html>
<html lang="en" class="[scrollbar-gutter:stable]">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="csrf-token" content={get_csrf_token()} />
    <.live_title suffix=" · Phoenix Framework">
      <%= assigns[:page_title] || "Ecommerce" %>
    </.live_title>
    <link phx-track-static rel="stylesheet" href={~p"/assets/app.css"} />
    <script defer phx-track-static type="text/javascript" src={~p"/assets/app.js"}>
    </script>
  </head>
  <body class="bg-white antialiased">
    <%= @inner_content %>
  </body>
</html>

lib/ecommerce_web/controllers/item_html/edit.html.heex
<.header>
  Edit Item <%= @item.id %>
  <:subtitle>Use this form to manage item records in your database.</:subtitle>
</.header>

<.item_form changeset={@changeset} action={~p"/items/#{@item}"} />

<.back navigate={~p"/items"}>Back to items</.back>

lib/ecommerce_web/controllers/item_html/index.html.heex
<.header>
  Listing Items
  <:actions>
    <.link href={~p"/items/new"}>
      <.button>New Item</.button>
    </.link>
  </:actions>
</.header>

<.table id="items" rows={@items} row_click={&JS.navigate(~p"/items/#{&1}")}>
  <:col :let={item} label="Name"><%= item.name %></:col>
  <:col :let={item} label="Description"><%= item.description %></:col>
  <:col :let={item} label="Price"><%= item.price %></:col>
  <:action :let={item}>
    <div class="sr-only">
      <.link navigate={~p"/items/#{item}"}>Show</.link>
    </div>
    <.link navigate={~p"/items/#{item}/edit"}>Edit</.link>
  </:action>
  <:action :let={item}>
    <.link href={~p"/items/#{item}"} method="delete" data-confirm="Are you sure?">
      Delete
    </.link>
  </:action>
</.table>

lib/ecommerce_web/controllers/item_html/item_form.html.heex
<.simple_form :let={f} for={@changeset} action={@action}>
  <.error :if={@changeset.action}>
    Oops, something went wrong! Please check the errors below.
  </.error>
  <.input field={f[:name]} type="text" label="Name" />
  <.input field={f[:description]} type="text" label="Description" />
  <.input field={f[:price]} type="number" label="Price" step="any" />
  <:actions>
    <.button>Save Item</.button>
  </:actions>
</.simple_form>

lib/ecommerce_web/controllers/item_html/new.html.heex
<.header>
  New Item
  <:subtitle>Use this form to manage item records in your database.</:subtitle>
</.header>

<.item_form changeset={@changeset} action={~p"/items"} />

<.back navigate={~p"/items"}>Back to items</.back>

lib/ecommerce_web/controllers/item_html/show.html.heex
<.header>
  Item <%= @item.id %>
  <:subtitle>This is a item record from your database.</:subtitle>
  <:actions>
    <.link href={~p"/items/#{@item}/edit"}>
      <.button>Edit item</.button>
    </.link>
  </:actions>
</.header>

<.list>
  <:item title="Name"><%= @item.name %></:item>
  <:item title="Description"><%= @item.description %></:item>
  <:item title="Price"><%= @item.price %></:item>
</.list>

<.back navigate={~p"/items"}>Back to items</.back>